on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t bcl2fastq .
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: Test the image
      run: docker run bcl2fastq --no-lane-splitting -R unit_test_data -o unit_test_data/output
    - name: Tag and Push the Image
      run: |
          docker tag bcl2fastq eferos93/bcl2fastq:latest
          docker push eferos93/bcl2fastq
   # - name: Build and push Docker image
    #  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #  with:
    #    context: .
    #    push: true
     #   tags: eferos93/bcl2fastq 
